// Copyright 2018-2019 VMware, Inc. 
// SPDX-License-Identifier: Apache-2.0


// This package is generated by client-gen with custom arguments.

// This package contains the scheme of the automatically generated clientset.
package scheme
