// Copyright 2018-2019 VMware, Inc. 
// SPDX-License-Identifier: Apache-2.0

// This file was automatically generated by lister-gen

package v1alpha3

// VirtualServiceListerExpansion allows custom methods to be added to
// VirtualServiceLister.
type VirtualServiceListerExpansion interface{}

// VirtualServiceNamespaceListerExpansion allows custom methods to be added to
// VirtualServiceNamespaceLister.
type VirtualServiceNamespaceListerExpansion interface{}
