// Copyright 2018-2019 VMware, Inc. 
// SPDX-License-Identifier: Apache-2.0

// This package is generated by client-gen with custom arguments.

// Package fake has the automatically generated clients.
package fake
