// Copyright 2018-2019 VMware, Inc. 
// SPDX-License-Identifier: Apache-2.0

// This package is generated by client-gen with custom arguments.

// This package has the automatically generated fake clientset.
package fake
