// Copyright 2018-2019 VMware, Inc. 
// SPDX-License-Identifier: Apache-2.0

// This file was automatically generated by informer-gen

package v1alpha3

import (
	internalinterfaces "github.com/heptio/quartermaster/custom/client/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// VirtualServices returns a VirtualServiceInformer.
	VirtualServices() VirtualServiceInformer
}

type version struct {
	internalinterfaces.SharedInformerFactory
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory) Interface {
	return &version{f}
}

// VirtualServices returns a VirtualServiceInformer.
func (v *version) VirtualServices() VirtualServiceInformer {
	return &virtualServiceInformer{factory: v.SharedInformerFactory}
}
