// Copyright 2018-2019 VMware, Inc. 
// SPDX-License-Identifier: Apache-2.0

// This file was automatically generated by informer-gen

package virtualservice

import (
	internalinterfaces "github.com/heptio/quartermaster/custom/client/informers/externalversions/internalinterfaces"
	v1alpha3 "github.com/heptio/quartermaster/custom/client/informers/externalversions/virtualservice/v1alpha3"
)

// Interface provides access to each of this group's versions.
type Interface interface {
	// V1alpha3 provides access to shared informers for resources in V1alpha3.
	V1alpha3() v1alpha3.Interface
}

type group struct {
	internalinterfaces.SharedInformerFactory
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory) Interface {
	return &group{f}
}

// V1alpha3 returns a new v1alpha3.Interface.
func (g *group) V1alpha3() v1alpha3.Interface {
	return v1alpha3.New(g.SharedInformerFactory)
}
